version: 2.1

jobs:
  workspace-demo:
    docker:
      - image: cimg/base:stable   # basic Linux environment
    steps:
      - checkout                  # pulls your repo code
      - run:
          name: Create Text File
          command: echo "This is a file created in CircleCI workspace" > hello.txt
      - run:
          name: List Files
          command: ls -l
      - run:
          name: Show File Contents
          command: cat hello.txt

workflows:
  version: 2
  demo-workflow:
    jobs:
      - workspace-demo

