version: 2.1

jobs:
  workspace-demo:
    docker:
      - image: cimg/base:stable   # basic Linux environment
    steps:
      - checkout                  # pulls your repo code
      
      - run:
          name: List Files
          command: ls 
      - run:
          name: Show sample file Contents
          command: cat sample.txt

workflows:
  git-integration-workflow:
    jobs:
      - git-integration-job

